---
- name: install unarchive module pkgs...
  become: '{{ unarchive_deps_privilege_escalation }}'
  become_user: '{{ unarchive_deps_privilege_escalation_user }}'
  block:
    - name: install OS packages
      package:
        name: '{{ unarchive_deps_all_pkgs + unarchive_deps_tar_pkgs + unarchive_deps_xz_pkgs }}'
        state: present
  ignore_errors: yes
