---
- name: Reload initd
  command: initctl reload-configuration

- name: Restart kafka service
  service:
    name: kafka
    state: restarted
  when: kafka_restart

- name: Restart kafka systemd
  systemd:
    name: kafka
    state: restarted
    daemon_reload: yes
  when: kafka_restart

- name: Restart ZooKeeper service
  systemd:
    name: zookeeper.service
    state: restarted
    daemon_reload: yes
  when: zookeeper_restart
